name: Wheelo
version: 0.0.1
description: Website for Wheelo
author: Louise van der Lith
repository: https://github.com/louisevanderlith/wheelo
environment:
  sdk: '>=2.0.0 < 3.0.0'
dev_dependencies:
  build_runner: '>=1.0.0 <2.0.0'
  build_web_compilers:
dependencies:
  mango_ui: '^1.0.3'
  mango_leads: '^1.0.2'
  dart_toast: '^0.3.0'
  mango_artifact: '^1.0.1'
  mango_vehicle: '^1.0.8'